baseURL  =  "https://immmmm.com"
languageCode = "zh-CN"
# DefaultContentLanguage = "zh-CN"
title  =  "wenzisay"
subtitle = "文子的自言自语"

theme  =  "hello-friend"
summaryLength = 140
hasCJKLanguage = true
# 每页显示的文章数量用于分页
paginate =  10
# rss 输出数量
rssLimit = 5

ignoreErrors = ["error-remote-getjson","error-remote-getcsv"]

[permalinks]
  posts = "/:filename/"
  tags = "/tags/:slug/"

[menu]
#  [[menu.main]]
#  name="哔哔"
#  url="/bbs/"
#  weight="1"
#  [[menu.main]]
#  name="友圈"
#  url="/friends/"
#  weight="2"
  [[menu.main]]
  name="归档"
  url="/archives/"
  weight="3"
#  [[menu.main]]
#  name="导航"
#  url="https://edui123.com/"
#  weight="4"
#  [[menu.main]]
#  name="关于"
#  url="/about/"
#  weight="5"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # Enable to show reading time in minutes for posts
  showReadingTime = false
  logoText = "hello friend"

  MenuMore = "更多"
  DateFormatList = "2006-01-02 15:04:05"
  DateFormatSingle = "2006-01-02 15:04:05"
  ReadMore = "阅读全文"

  EditPath = 'https://github.com/lmm214/immmmm/edit/master/content'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
    
[outputs]
  home = ["Atom", "HTML","JSON"] # <domain>/atom.xml
  page = ["HTML"]
  
[outputFormats.Atom]
  mediatype = "application/rss"
  baseName = "atom"

[params.twikoo]
	enable = true

